# Generated by Django 5.1.3 on 2024-11-30 15:55

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielanguages',
            name='languages',
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language',
            field=models.CharField(default='English', max_length=16),
        ),
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(upload_to='actor_images/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='moments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='moments',
            name='movie_moments',
            field=models.ImageField(upload_to='moments'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(upload_to='movie_image/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=62),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], max_length=16),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=16),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=16),
        ),
    ]
